name: Deploy WordPress Theme

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Theme to WordPress Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install sshpass

      - name: Sync theme files
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD rsync -avz --delete -e 'ssh -p 22 -o StrictHostKeyChecking=no' ./ $USERNAME@$HOST:/robaglia.fr/wp-content/themes/RobagliaArchitect